### ISSUE TITLE
Not able to open site http://sec-mooc-1.cs.helsinki.fi:7831/ on chapter 2

### ISSUE THREAD

**Issue by subratrout** [cybersecuritybase/cybersecuritybase.github.io#23]
Not sure this is the right place to post. But I can't access http://sec-mooc-1.cs.helsinki.fi:7831/ which is mentioned on ch-2 "The Byteless are coming to town!".

**Comment by nygrenh** [comment]
Sounds weird. The link you provided opens just fine on my machine.

**Comment by subratrout** [comment]
I am from US and using a wireless connection. Does it make any difference?

**Comment by nygrenh** [comment]
It should not. The site should be reachable from there too. Can you provide the error message your browser is giving? (or the output of `curl -v http://sec-mooc-1.cs.helsinki.fi:7831/` if you have curl on your machine)

**Comment by subratrout** [comment]
*   Trying 86.50.18.10...
* connect to 86.50.18.10 port 7831 failed: Connection refused
* Failed to connect to sec-mooc-1.cs.helsinki.fi port 7831: Connection refused
* Closing connection 0
curl: (7) Failed to connect to sec-mooc-1.cs.helsinki.fi port 7831: Connection refused

**Comment by nygrenh** [comment]
That's weird. What happens if you try to ping the machine? (`ping sec-mooc-1.cs.helsinki.fi`) Can you reach `cs.helsinki.fi`?

**Comment by subratrout** [comment]
64 bytes from 86.50.18.10: icmp_seq=0 ttl=42 time=175.921 ms
64 bytes from 86.50.18.10: icmp_seq=1 ttl=42 time=176.593 ms
64 bytes from 86.50.18.10: icmp_seq=2 ttl=42 time=175.826 ms
64 bytes from 86.50.18.10: icmp_seq=3 ttl=42 time=175.774 ms
64 bytes from 86.50.18.10: icmp_seq=4 ttl=42 time=176.084 ms

**Comment by subratrout** [comment]
--- sec-mooc-1.cs.helsinki.fi ping statistics ---
95 packets transmitted, 93 packets received, 2.1% packet loss
round-trip min/avg/max/stddev = 175.364/177.121/206.728/3.540 ms

**Comment by nygrenh** [comment]
What's your internet service provider? Does it block access to unusual ports? Can you access `http://sec-mooc-1.cs.helsinki.fi:50001/`?

**Comment by subratrout** [comment]
I can access http://sec-mooc-1.cs.helsinki.fi:50001 from my phone but not from my computer. So I think my network provider is blocking it.

**Comment by nygrenh** [comment]
Since your ISP seems to be the source of the problem, I recommend either looking into tethering options or getting a VPN.

**Comment by subratrout** [comment]
Yes, will do that. Thank you.
