### ISSUE TITLE
Part 5: wrong answer limit in DevOps quiz

### ISSUE THREAD

**Issue by kingslef** [cybersecuritybase/cybersecuritybase.github.io#26]
In the quiz about DevOps in part 5 it says the following:
> Consider the DevOps movement where developers are given the access to the production systems and the responsibility to maintain them. What security issues arise over the traditional setup, where a separate systems administration team are in control of the production servers? In addition, what are the benefits of such changes? Limit your answer to 300 characters.

The limit should be `300 words`, right?

**Comment by nygrenh** [comment]
The limit should've been 300 words but it's too late to correct the problem since too many people have followed 300 characters limit and we don't want to treat them unfairly.

**Comment by kingslef** [comment]
I see, thanks!
