### ISSUE TITLE
Securing Software of CSB-2017 with broken(?) start-date.

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#33]
Hello,

Looks like that even https://cybersecuritybase.github.io/ is ready for CSB-2017 launch: current page and start date of 'Securing Software'-part with potentially outdated-view (or mistake for month/year).
I able to think that expected date is 06.11.2017. Or also "unknown". @nygrenh 

Thanks.

**Comment by nygrenh** [comment]
Should be fixed now. Thanks!
