### ISSUE TITLE
Microsoft Edge and 'notification' about potential troubles under web-based materials.

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#35]
Hello,

Most likely it discussed already.. but I completed previous launch of CSB with Microsoft Edge.
From those days, Microsoft Edge has received many improvements, fixes and some other tweaks.

But CSB-2017 course-material's pages still with next notification under Edge browser (too):

`Some parts of this page might not work on your current browser. Consider switching to either Chrome or Firefox.`

Does this notification is reasonable one? I able to think about some things which should not work with Edge (and work with Firefox/Chrome), but does it 'in use' with cybersecuritybase.github.io?
Or does it known what kind of parts might not work with Microsoft Edge?

Or maybe it can be OK to use Microsoft Edge (Windows 10 64bit) as officially recommended browser?

**Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299**

Sorry for not a critical concern.

Thanks!

**Comment by nygrenh** [comment]
Hi,

The main problem with Microsoft Edge is that we don't have time or resources to test that our sites work with it. So we're not sure if it's going to work and we won't guarantee that we won't break the site on Edge in the future.

If you really want to use Edge you can try and see for yourself if it works!
