### ISSUE TITLE
URL to https://wiki.theory.org/YourLanguageSucks is not direct link.

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#37]
Hello,

This URL is noted with first part of Securing Software course.

> Whilst one may think that [Java sucks](https://wiki.theory.org/YourLanguageSucks), it can -- in the end -- be a decent language to work with due to, among other things, static typing, a good developer base, and an abundance of high-quality libraries and developer tools.

and URL to https://wiki.theory.org/YourLanguageSucks is not direct link to:
https://wiki.theory.org/index.php/YourLanguageSucks

Just because this is not a critical point - sorry for ask - but what if it should not be with this state.

Thanks!

**Comment by nygrenh** [comment]
Should be fixed now, thanks!
