### ISSUE TITLE
""Who wants to be a millionaire?"" does not require to be answered to perform peer-review.

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#38]
Hello,

I feel that this point can not be critical. But just interesting:

With Part-Two of Securing Software and with "Who wants to be a millionaire?"-quiz:
- we're able to perform peer-review (check other answers and review it).
- and we're able do not answer/complete quiz before it.

`and, yes, by 'ability' to perform peer-review (to see other answers) - I meant designed steps (not an available tricks which was always there). By 'designed steps' - required only to open Part-two page and be logged.`

Does it should be with this view? Previous quizzes (Part-One) do not allow it.

Sorry for this ask.

Thanks!

**Comment by nygrenh** [comment]
Should be fixed now. Thanks!

**Comment by Hlynrkjaer** [comment]
Hello,

@nygrenh , looks like that with CSB-2017 Advanced Topics -> Part TWO.
The "Future directions?" does not require to be answered to perform peer-review.
All three peer-reviews with visible answers even before our own answer.
Maybe it is expected situation; and maybe it is already not an actual point to fix (since !? some weeks how). But anyway.

Thanks!
