### ISSUE TITLE
OWASP Top 10 - 2017 is released (?!).

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#39]
Hello,

Concerned next words of Part-Three (Securing Software):

> One of the important lists that they maintain is the [OWASP Top 10](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project) which contains a list of the ten most critical web application security risks. The most recent list is from [2013](https://www.owasp.org/index.php/Top10#OWASP_Top_10_for_2013), **and an updated list will be released either late 2016 or in 2017**.

I thought that recently was second release candidate for OWASP-Top-Ten-2017 and decided to open their OWASP-Top-Ten-Project page. Where, today, possible to see that:

> OWASP Top 10 2017 Released
> The  [OWASP Top 10 - 2017](https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf) is now available. 

Probably only first days... but maybe will be good to note it under material (not as only potential release).

Thanks!

**Comment by nygrenh** [comment]
Hi,

Good point, we'll consider updating the material. However it might be too late to do it for this year's iteration.
