### ISSUE TITLE
Cross-site Request Forgery: (CRSF) -> (CSRF)

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#41]
Hello,

Part-Three of Security Software course with next words:

> 1.8. Cross-site Request Forgery
Cross-site Request Forgery (**CRSF**) makes it possible to create requests from another site (source) to the web application (target). If the user who is accessing the source site is authenticated to the target web application, the browser of the user will send an authentication token (e.g. cookie) with the request to the target application as the user is accessing the source site, making it possible to access data as an authenticated user that should not be accessible.

Does "CRSF" should be "**CSRF**"?

Thanks!

**Comment by nygrenh** [comment]
Fixed. Thanks!
