### ISSUE TITLE
Part-Four of Securing Software course and "How to pass the course"-notification.

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#44]
Hello,

Sorry for this strange ask.

Currently all of previous parts (one, two, three) of Securing Software course starts with "
**How to pass the course**"-note. 

But Part-Four do not contain such. I able to suspect that it's OK (but strange that all of previous parts with this 'note' at first).

Thanks!

**Comment by Hlynrkjaer** [comment]
Valid for "Part-Five of Securing Software course" too.

**Comment by nygrenh** [comment]
Yeah, I didn't copy paste it initially there because the conditions were going to be the same. But I have now included the same banner in those pages too.
