### ISSUE TITLE
CSB-2017 Advanced Topics Part Three comes with answered Quizzes.

### ISSUE THREAD

**Issue by Hlynrkjaer** [cybersecuritybase/cybersecuritybase.github.io#50]
Hello,

Sorry for this discussion.

With my experience (and I'm with experience about previous CSB launch) Advanced Topics Part Three for CSB-2017 with view like:

- all Quizzes of Part-Three were marked as answered with first-time opening this Part-Three (and indeed answer is chosen and there is statement about). Does it re-use from previous CSB-launch?
Or something wrong locally (?!). 

Even it should not be a critical point but just looks a little be strange.

Thanks!

**Comment by nygrenh** [comment]
No, there's nothing wrong, we simply decided to re-use those quizzes from last year.

Sorry about the confusion!

**Comment by Hlynrkjaer** [comment]
Hello,

Thanks for clarification and response.
It is a good decision, in fact.
- - - -
I feel that it is OK to re-answer Quizzes (like re-transfer answer). When possible to do so. Just like doublecheck that answer is received. :)

Thanks!
