### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MHM5000** [cybersecuritybase/cybersecuritybase.github.io#6]
Hi
What's the license of this project?
MIT?

**Comment by kimmoal** [comment]
From the footer: http://mooc.fi/courses/2016/cybersecurity/
**All the material is licensed under Creative Commons BY-NC-SA.**

**Comment by avihavai** [comment]
Hi @MHM5000 and thanks for the question! As @kimmoal noted, we're using Creative Commons whenever possible. Parts of the material is not yet written, and for those parts we'll use the license that the authors of those specific parts wish to use. We will make the license more explicit in the future.
